db:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - /volumes/data:/var/lib/postgresql/data
web:
  build: ./researchnet
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db:db
juptyer:
  image: jupyter/datascience-notebook
  volumes: 
   - ./notebooks:/home/jovyan/work
  ports:
    - "8888:8888"
  links:
    - db:db
nginx:
  build: ./nginx
  volumes_from:
    - web
  links:
    - web
  ports:
    - "80:80"