db:
  image: postgres
mongo:
  image: mongo
web:
  build: .
  command: python researchnet/manage.py runserver 0.0.0.0:8000
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db:db.local
    - mongo:mongo.local
juptyer:
  image: jupyter/datascience-notebook
  volumes: 
   - ./notebooks:/home/jovyan/work
  ports:
    - "8888:8888"
  links:
    - db:db.local
    - mongo:mongo.local