db:
  image: 'postgres:latest'
  ports:
    - '5432:5432'
  volumes:
    - /volumes/data:/var/lib/postgresql/data
web:
  build: ./researchnet
  links:
    - db
  ports:
    - '8000:8000'
nginx:
  build: ./nginx
  volumes_from:
    - web
  links:
    - web
  ports:
    - '80:80'
juptyer:
  image: jupyter/datascience-notebook
  volumes: 
   - ./notebooks:/home/jovyan/work
  ports:
    - '8888:8888'
  links:
    - db:db