db:
  image: postgres
  ports:
    - "5432:5432"
mongo:
  image: mongo
  ports:
    - "27017:27017"
web:
  build: .
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db:db
    - mongo:mongo
juptyer:
  image: jupyter/datascience-notebook
  volumes: 
   - ./notebooks:/home/jovyan/work
  ports:
    - "8888:8888"
  links:
    - db:db
    - mongo:mongo